### ISSUE TITLE
Wrong calculation values if the number is less than 10

### ISSUE THREAD

**Issue by sreshetnyak** [openboy2012/FlickerNumber#2]
- (void)flickerAnimation:(NSTimer *)timer{
  long long rangeInteger = [timer.userInfo[DDRangeIntegerKey] longLongValue];
  self.flickerNumber = @([self.flickerNumber longLongValue] + rangeInteger);

rangeInteger value is always zero
- (void)flickerAnimation:(NSTimer *)timer{
  float rangeInteger = [timer.userInfo[DDRangeIntegerKey] floatValue];
  self.flickerNumber = @([self.flickerNumber floatValue] + rangeInteger);

need to take a float value

**Comment by openboy2012** [comment]
thanks, I have fixed it as your suggest.

**Comment by sreshetnyak** [comment]
Thank you if you do not make it more difficult to upgrade in pods

**Comment by openboy2012** [comment]
please use the version 1.0.1 on pods, I will close the issue#2

**Comment by jxbaoweiyj** [comment]
if ([timer.userInfo[DDRangeIntegerKey] floatValue] >= 1.0) {

crash at here

**Comment by openboy2012** [comment]
@jxbaoweiyj  what's the sence when crashed?
